export const DEFAULT_GROCERY_ITEMS = [
  { store: "Walmart", name: "Chicken Breast", have: false },
  { store: "Walmart", name: "Salmon Fillet", have: false },
  { store: "Walmart", name: "Eggs", have: false },
  { store: "Walmart", name: "Cherry Tomatoes", have: false },
  { store: "Walmart", name: "Egg Whites", have: false },
  { store: "Walmart", name: "Whole grain bread", have: false },
  { store: "Walmart", name: "Greek yoghurt", have: false },
  { store: "Walmart", name: "Cottage Cheese", have: false },
  { store: "Walmart", name: "Mixed Vegetables", have: true },
  { store: "Walmart", name: "Nuggets", have: true },
  { store: "Walmart", name: "Instant Noodles", have: true },
  { store: "Walmart", name: "Omega 3", have: true },
  { store: "Walmart", name: "Milk", have: false },
  { store: "Walmart", name: "Banana", have: false },
  { store: "Walmart", name: "Strawberries", have: false },
  { store: "Walmart", name: "Juice", have: false },
  { store: "Walmart", name: "Chili", have: false },
  { store: "Walmart", name: "Bottled water", have: false },
  { store: "Walmart", name: "Onion", have: false },
  { store: "Walmart", name: "Paneer", have: true },
  { store: "Walmart", name: "Cereal", have: true },
  { store: "Walmart", name: "Tomato", quantity: "3", have: false },
  { store: "Walmart", name: "Garlic & Ginger Paste", have: true },
  { store: "Walmart", name: "Mixed Salad", have: true },
  { store: "Walmart", name: "Tofu", have: true },
  { store: "Walmart", name: "Chia seeds", have: true },
  { store: "Walmart", name: "Frozen Berries", have: true },
  { store: "Walmart", name: "Paprika", have: true },
  { store: "Walmart", name: "Garlic Powder", have: true },
  { store: "Walmart", name: "Rice", have: true },
  { store: "Walmart", name: "Oats", have: true },
  { store: "Walmart", name: "Salt", have: true },
  { store: "Walmart", name: "Calcium", have: true },
  { store: "Walmart", name: "Parchment Paper", have: true },
  { store: "Walmart", name: "Almonds", have: true },
  { store: "Walmart", name: "Olive oil", have: true },
  { store: "Walmart", name: "Coffee", have: true },
  { store: "Walmart", name: "Tortilla", have: false },
  { store: "Walmart", name: "Dates", have: false },
  { store: "Walmart", name: "Pumpkin Seed Oil", have: false },
  { store: "Walmart", name: "Bodywash", have: false },
  { store: "Walmart", name: "Laundry Detergent", have: false },
  { store: "Walmart", name: "Dishwasher Detergent", have: false },
  { store: "Walmart", name: "Scrub", have: false },
  { store: "Walmart", name: "Gastric Tablet", have: true },
  { store: "Walmart", name: "Napkins", have: true },
  { store: "Walmart", name: "CeraVe Cleanser", have: true },
  { store: "Walmart", name: "Pimple Patch", have: true },
  { store: "Dollarama", name: "Gloves", have: true },
  { store: "Dollarama", name: "Dryer sheets", have: true },
  { store: "Dollarama", name: "Paper towel", have: true },
  { store: "Dollarama", name: "Air freshner", have: true },
  { store: "Dollarama", name: "Scrub", have: true },
  { store: "Dollarama", name: "Cleaning Cloth", have: true },
  { store: "Dollarama", name: "Toothpaste", have: true },
  { store: "Dollarama", name: "Floss", have: true },
  { store: "Dollarama", name: "Ziplock", have: true },
];
